### ISSUE TITLE
plugin de gestion des quotas logiques

### ISSUE THREAD

**Issue by antoine-mesobfc** [mesocentre-mcia/ansible-collection-irods#4]
Bonjour,

Dans le cadre du projet MesoNet, nous avons besoin de gérer des quotas logiques avec le plugin [logical quotas](https://github.com/irods/irods_rule_engine_plugin_logical_quotas)

Ce plugin requiert l'ajout de quelques lignes dans la partie `rule_engines` du  `server_config.json`, mais pas n'importe où (de préférence au tout début du bloc)

https://github.com/mesocentre-mcia/ansible-collection-irods/blob/4d19581760c9069121739b9f56ca87439eeb515b/roles/irods/templates/v4/server_config.json.j2#L93)

Le reste de la configuration et de l'installation du plugin peut être fait dans un rôle à part, mais c'est la collection qui gère le fichier de configuration `server_config.json` donc ça me semble plus opportun de le faire ici.

Je proposais à Alexandra de simplement placer quelques variables (voir même des boucles sur des listes) à certains endroits du template pour pouvoir facilement le personnaliser via des rôles extérieurs à la collection, ce qui serait peut être utilise pour d'autres besoins.

Je vois qu'il y a eu un ajout pour `rule-engine-python`, cette méthode pourrait convenir aussi pour `logical_quotas` en le plaçant en début de bloc, mais cela impliquerait que la collection gère ce plugin complétement.

Qu'en pensez vous ?

Antoine

**Comment by pigay** [comment]
Bonjour,

Je viens de pousser un commit qui devrait permettre de configurer le rule engine avec l'ordre qu'on veut: 00a0d414918040f0bdf2abdd68f776d2cd4b3d10

Pour l'utiliser, tu peux redéfinir la variable `irods_rule_engines`. La valeur par défaut est:

```yaml
irods_rule_engines:
  - name: irods_rule_engine_plugin-irods_rule_language-instance
    configuration: irods_rule_language

  - name: irods_rule_engine_plugin-cpp_default_policy-instance
    configuration: cpp_default_policy
```

Tu peux la modifier pour ajouter le plugin rule engine python par exemple:

```yaml

irods_rule_engines:
  - name: irods_rule_engine_plugin-python-instance
    configuration: python

  - name: irods_rule_engine_plugin-irods_rule_language-instance
    configuration: irods_rule_language

  - name: irods_rule_engine_plugin-cpp_default_policy-instance
    configuration: cpp_default_policy
 ```

Comme c'est une liste, l'ordre compte.

Pour ajouter un engine avec une configuration différente, tu peux fair la définition dans la variable `irods_rule_engines_extra_configurations` en t'inspirant de la variable `irods_rule_engines_configurations` définie ici: https://github.com/mesocentre-mcia/ansible-collection-irods/blob/00a0d414918040f0bdf2abdd68f776d2cd4b3d10/roles/irods/vars/main.yml#L23

pour résumer, le champ `configuration` dans `irods_rule_engines` fait référence à une entrée dans `irods_rule_engines_configurations` ou `irods_rule_engines_extra_configurations`.
Le contenu de cette configuration est injecté directement dans le fichier server_config.json (traduit du yaml vers du json).

Dis-moi qi ça convient.

Pierre
